CEdev/demos/demo0/README.md, CEdev/demos/template/Makefile, CEdev/demos/template/README.md, CEdev/demos/template/main.c
A few initial improvements to the demo directory:
- Made demo0 less of a template and more of a demo. I still need to debug
why it crashes on quit.
- Simplified the template-ish parts of demo0 into a new template directory.
=> Improved demo0 "purity", moved template-like stuff to a template dir

CEdev/lib/src/graphics/graphx/graphics_lib.asm
Looking for a sanity check that this code is correct.
=> Optimized _TilePtrMapped

src/graphx/graphx.asm
=> Optimize gfx_FillScreen and gfx_ZeroScreen

src/graphx/graphx.asm
Reverts CE-Programming/toolchain#87
=> Revert "Few opts"

src/graphx/graphx.asm
imported PR from https://github.com/CE-Programming/toolchain/pull/115 so that travis can run the tests
=> (grosged) slight optimisations

src/graphx/graphx.asm
taken time : now **175** instead of 193
=> PrintStringXY_Clip optimised

src/graphx/graphx.h
=> Incorrect word

src/graphx/graphx.asm
"Unrolled" in 3 parts in order to have less comparisons inside main loop.
=> An optimisation of _PrintNormalFont

examples/hello_world/src/main.c
The comment changes should make the program less confusing. The change to the printTextSmall function will enable text to be printed farther to the right, past 255 pixels.
=> Improved comments and printTextSmall function

src/ce/tice.h
Added description for the lcd_BacklightLevel macro.
=> lcd_BacklightLevel

examples/fontlib_example/autotester.json, examples/fontlib_example/src/main.c, src/fontlibc/fontlibc.asm, src/fontlibc/fontlibc.h
adds basic scrolling in a text window and scrolling can be triggered automatically. Also fixes an off-by-one bug in ClearEOL and adds a clarifies bunch of documentation.
=> Add a new scrolling feature to FontLibC

examples/standalone/second_counter/src/main.c, examples/standalone/second_counter2/src/main.c, src/ce/debug.h, src/ce/intce.h, src/ce/tice.h, src/graphx/graphx.h, src/keypadc/keypadc.h, src/std/float.h, src/std/format.h
Add parentheses and volatile where necessary.
=> Fix defines

src/fileioc/fileioc.h
https://www.cemetech.net/forum/viewtopic.php?t=17915
I added the changes that I wanted. I just added one example function. Maybe next time someone who reads the documentation won't make the same mistake as me.
=> added clarifications to fileioc

src/ce/delay.src, src/ce/sleep.src, src/ce/ticksleep.src, src/ce/usleep.src, src/std/shared/clock.src
=> Fix occasional bug in `delay()` and `usleep()`

src/std/static/acos.src
=> Pop arguments after calling _asin

.github/workflows/make.yml
Add retries and only try to codesign when secrets are available (i.e. not on forks).
=> CI: macOS: improve codesigning etc.

docs/libraries/keypadc.rst
Dection → Detection
Pretty self-explanatory.
=> Fix heading spelling of keypadc.h docs

src/ce/getstringinput.src
What is with all of these magic values in this routine?
Also, please test this.
=> Change large if, elif chain of consecutive values in GetStringInput to one comparison

.gitmodules
=> Fix GraphX template submodule

src/libc/isdigit.src, src/libc/isgraph.src, src/libc/islower.src, src/libc/isupper.src
I have verified these 4 functions work.
I rewrote
```
add a, -N
sbc hl, hl
inc hl
ret
```
to
```
sub a, N
sbc hl, hl
ret
```
Proof they are equivalent (for routines where every nonzero value is considered true):
```
; Assume A = some value K
add a, -N	; a = K-N, Carry flag set iff K + (256-N) >= 256, AKA K>= N
sbc hl, hl	; hl = if K >= N then -1 else 0
inc hl	; hl = if K >= N then 0 else 1
; AKA if K < N then 1 else 0
ret
```
```
; Assume A = some value K
sub a, N	; a = K-N, Carry flag set iff K - N < 0, AKA K < N
sbc hl, hl	; hl = if K < N then -1 else 0
ret
```
=> Optimize isdigit, isgraph, islower, isupper

docs/headers/ti/index.rst, docs/headers/ti/sprintf.rst, docs/static/printf.rst, src/ce/include/ti/sprintf.h, src/libc/errno_str.c, src/libc/include/stdio.h, test/standalone/asprintf_fprintf/src/main.c
Fixed the documentation for `boot_sprintf`
=> changed boot_sprintf.h to ti/sprintf.h and fixed the documentation
