CEdev/examples/template/Makefile

This allows us to, for example, portably include files from subdirectories:
SOURCES = $(wildcard *.c) $(subst /,\,$(wildcard */*.c))
(note: if your shell supports "globstar" you can use `**/*.c` to recursively include from subdirectories)

Increase subdirectory portability

---

CEdev/examples/template/Makefile

Today's experiments with subdirectory support (and logging ez80cc file system use via process monitor) seem to show these environment variables are useless.

These environment variables are unused

---

CEdev/examples/template/Makefile

This guarantees that all .obj and .src files created by the build process are removed, even if other directories are added down the line.

More portable deletion of build products

---

CEdev/lib/src/libraries/graphics_src/graphx/v2/graphics_lib.asm

Unrolled each of the opaque and transparent braches into four iterations, so stretches of the same pixel opaqueness/transparency mostly fall through the jumps and execute faster.
Before (12 bytes):
* opaque->opaque: 41 cc
* opaque->trans: 36 cc
* trans->opaque: 46 cc
* trans->trans: 41 cc
After (54 bytes; lists cycles after 1/2/3/4 mod 4 iterations in a row of previous pixel state):
* opaque->opaque: 36/36/36/41 cc 
* opaque->trans:  41/41/41/36 cc
* trans->opaque: 38/38/38/46 cc
* trans->trans: 33/33/33/38 cc
Starts on the fast transparent path based on the assumption that the majority of transparent sprite pixel rows start with a transparent pixel, as transparency is often used to draw "cutout" images.

Optimized _TransparentPlot_ASM for speed*

---

CEdev/lib/src/libraries/graphics_src/graphx/v2/graphics_lib.asm

-modified length check : replaced "dec b" with "xor a \ or b"
-optimised a little the drawing

_VertLine_NoClip improvements

---

CEdev/lib/src/libraries/graphics_src/graphx/v2/graphics_lib.asm

suggest a faster FillCircle_NoClip routine

---

CEdev/lib/src/graphics/graphx/v2/graphics_lib.asm

Slight optimisation of _PrintUInt,
Propose to include a faster fillscreen when color is null

optimised _PrintUInt & _FillScreen

---

CEdev/lib/src/graphics/graphx/graphics_lib.asm

This doesn't actually work. I totally blanked on the fact that the function arguments need to be kept on the stack.

Revert "Optimized _TilePtrMapped"

---

CEdev/lib/src/graphics/graphx/graphics_lib.asm

In the process, I eliminated the unclipped version and the _SetTextConfig code that switched between it and the clipped version. The new clipped version is faster than the old unclipped version and should provide the same behavior given onscreen coordinates.

Optimized _SetTextXY

---

src/fileioc/fileioc.asm

_Get_Tok_Strng calls the token hook, which needs bit 0, (iy+$35) or so, and if iy is random, it might happen that the OS things the hook is set, while it isn't, and then it resets the bit.

Reset iy for token hook

---

src/graphx/graphx.asm

Can someone confirm that this is both correct and desired?
Also, this is a lazy way of running all the autotests to see if any need to be updated.

Calculate green LSB in default palette colors

---

src/fileioc/fileioc.asm
src/fileioc/fileioc.h

Useful if you want to get the name of the slot variable for example.

Add ti_GetVATPtr

---

src/fileioc/fileioc.asm

ti_DetectAny( didn't overwrite the variable type, it only writes them to the stack entry, which is wrong obviously. This PR fetches the address of the type var and writes the type of the variable to this address.

Properly overwrite the variable type

---

src/graphx/graphx.asm

Reverts CE-Programming/toolchain#196
Pretty sure this doesn't work for characters with a width other than 8. The original PR #196 really needed more review before merging.

Revert "An optimisation of _PrintNormalFont"

---

src/ce/getstringinput.src

Behavior was: 
1. pqr will put "pqr\0" in the buffer
2. pqrs will put "pqrs\0" in the buffer
3. pqrst will put "pqrst" in the buffer (no NUL)
4. pqrstu will put "pqrst" in the buffer (as above, can not type the u)

Save and restore clobbered DE register

---

src/fileioc/fileioc.asm
src/fileioc/fileioc.h

When a gc will be triggered as a result of calling _Arc_Unarc, set OS graphics mode, restore afterwards.
Added ti_SetPostGCHandler((void)(*routine)(void)) so user programs can easily setup graphics again.
Had to replace some of the files in src/include/ to get fileioc to build. Ignore those if you can lol
GC handler functionality has been tested using the attached program.
[archive_overloader.zip](https://github.com/CE-Programming/toolchain/files/4914759/archive_overloader.zip)

fileioc: improve garbage collect handling

---

.github/workflows/make.yml
docs/build.sh

This makes the documentation build script emit single-file HTML and LaTeX output as well as multi-file HTML since some users may prefer to have a single-file version of the documentation. The PDF currently doesn't build because it tries to use SVG graphics, however.
The documentation building action now also saves the documentation as an artifact.

Build documentation in a few formats

---

src/ce/tice.h

This previously didn't specify when -1, 0, and 1 were returned. Additional research was required to determine when each was returned.

Clarify os_RealCompare documentation.

---

docs/libraries/graphx.rst

Fix spelling

---

src/keypadc/keypadc.h

Correct the keyboard group number in the comment above #define kb_KeyAnnul in keypadc.h

Correct comment in keypadc.h

---

src/crt/bpopcnt.src
src/crt/ipopcnt.src
src/crt/ipopcnt_fast.src
src/crt/llpopcnt_fast.src
src/crt/lpopcnt.src
src/crt/lpopcnt_fast.src
src/crt/popcnt_common.src
src/crt/spopcnt.src
src/crt/spopcnt_fast.src

I've come up with a novel algorithm for more efficiently doing popcount on eZ80 (which really shines when operating on 16 bits at a time).
16-bit, 24-bit, and 32-bit implementations call into a common set of code for popcounting 16 bits efficiently. Meanwhile, the 8-bit implementation is also smaller and faster than the previous implementation. (Note that the previous 8-bit implementation would be more optimal in a Z80 CRT, though).
I also implemented unrolled, self-contained versions for 16-bit, 24-bit, and 32-bit, which may be useful once the toolchain supports linking them.
I exhaustively tested the 8-bit and 16-bit implementations, and tested the 24-bit and 32-bit implementations within reasonable doubt.
These are my calculations for the cycle savings compared to the previous impls …

Optimize popcount implementations

---

examples/standalone/math_test/autotest.json
examples/standalone/math_test/src/main.c
src/crt/lbswap.src
src/crt/llbswap.src

Goes in tandem with @jacobly0's recent llvm changes to emit calls to these.

Implement optimized `lbswap` and `llbswap`

---

src/libc/ishl.src

Similarly to the recent right-shift update, this bounds the execution time of 24-bit left shifts. It's slower for shifts by 0, 1, or 2, but the same or much faster for all other shifts. Constant shifts by 0-4 should be inlined by the compiler to avoid calls to this routine in the first place.

Optimize __ishl for bounded execution time for larger shifts

---

src/ce/include/ti/real.h
src/ce/include/ti/vars.h
src/fontlibc/fontlibc.h
src/graphx/graphx.h

Became "necessary" for the lua binding thing that didn't like anonymous structs.
I'm not sure which naming convention we should use, though, and maybe `_` as prefix isn't great, but it's been used in some places before already so I used that too.
We could also just use `the_type_name` for the struct name, and the typedef would still be `the_type_name_t`?

includes: add names to some structs.

---

src/ce/include/ti/vars.h

The TI-83+ link guide (http://merthsoft.com/linkguide/ti83+/vars.html#matrix) specifies that matrices are stored in row-major order. The OS_MATRIX_ELEMENT implementation performs memory lookups in column-major order. Basic testing confirms that the OS_MATRIX_ELEMENT indexes the matrix incorrectly.

Change OS_MATRIX_ELEMENT to row-major

---

src/graphx/graphx.asm

Fixes #427. Probably. I haven't actually tested it.

Fix 1-wide `gfx_Rectangle_NoClip`

---

src/libc/allocator.src
src/libc/allocator_simple.src

The calloc implementation was ignoring ABI when calling malloc and memset, by assuming the parameters on the stack would not be modified. This is certainly not the case in the new simple_malloc implementation, so calloc could cause a buffer overflow via the memset.
Also, I optimized simple_malloc because I could :)

Fix calloc ABI usage, optimize simple_malloc

---

src/ce/getstringinput.src
src/ce/gettokeninput.src

Builds off of the previous PR to implement more size optimizations (including some JP to JR conversions due to the reduced size, which is why I'm making a PR to verify the build)

More GetStringInput size optimizations

---

src/libcxx/include/type_traits

I noticed that `signed short` was absent from `<type_traits>`, causing `std::is_integral_v<signed short>` to return false.
```c++
#include <type_traits>
// passes
static_assert(std::is_integral_v<unsigned short>, "unsigned short is not integral");
// fails
static_assert(std::is_integral_v<signed short>, "signed short is not integral");
int main(void) {
return 0;
}
```

__integral<signed short> was missing from type_traits

---

src/usbdrvce/usbdrvce.h

Useful for using sizeof(/* structure */) when setting bLength so that you don't accidentally put the wrong number and ensuring memory layouts follow the standard.

Apply ((packed)) attribute to USB descriptor structures.

---

src/graphx/graphx.asm

Reworks sprite clipping to use range-based (unsigned) comparisons instead of signed comparisons, and also moves shared pointer calculation logic into the clipping routine. Additionally, logic is added to gfx_SetClipRegion to apply SMC to all clipping routines. This saves ~~178~~ 215 bytes overall, and I measured the following changes in cycle counts for gfx_Sprite (up until the gfx_Wait for drawn sprites, or through the return for culled sprites):
fully onscreen: 1177 -> ~~716~~ 644
clipped top: 1450 -> ~~860~~ 772
clipped left: 1488 -> ~~864~~ 780
clipped right: 1254 -> ~~756~~ 684
clipped bottom: 1202 -> ~~744~~ 672
clipped top left: 1761 -> ~~1008~~ 908
clipped top right: 1527 -> ~~900~~ 812
clipped bottom left: 1513 -> ~~892~~ 808
clipped bottom right: 1279 -> ~~784~~ 712
clipped …

Optimize graphx clipping logic

---

src/libcxx/include/concepts

Adds `same_as`, `integral`, and `floating_point` from the C++20 <concepts> header.
The second commit adds `signed_integral` and `unsigned_integral`, but they are dependent on https://github.com/CE-Programming/toolchain/pull/525

Add C++20 <concepts>

---

src/libc/include/cdefs.h
src/libcxx/include/bit
src/libcxx/include/type_traits
src/libcxx/type_traits.cpp

C++20 `<bit>` provides `std::bit_cast`, which allows for cleaner type punning. I have not implemented `popcount`, `rotr`, `countl_zero`, and others for the header yet.
```c++
int32_t y = *reinterpret_cast<int32_t*>(&x);
int32_t z = std::bit_cast<int32_t>(x);
```
The compiler supports `__is_trivial __is_trivially_copyable __is_standard_layout __is_pod __is_empty __is_polymorphic __is_abstract`, so I added them to `<type_traits>`. In addition to `is_compound`, `is_scalar`, and `is_object`. I also added some tests to `type_traits.cpp` for `is_signed` and `is_unsigned`.
Lastly, since `noexcept` isn't a keyword in C++98, I fixed the definition of `__NOEXCEPT` for `std=c++98` and `std=gnu++98`.

Added C++20 <bit>, added to <type_traits>, fixed __NOEXCEPT in C++98

---

src/crt/frem.src

```c
float fwrap(float x, float min, float max) {
if (min > max)
return fwrap(x, max, min);
return (x >= 0 ? min : max) + fmodf(x, max - min);
}
```
This code when compiled with `-Ofast` (in C) would emit a lib-call to `__frem` instead of a call `_fmodf`. However, `__frem` wasn't defined in the toolchain. This has been fixed by adding the CRT routine for `__frem`, which wraps `_fmodf` for now.
Credit to @merthsoft for finding this bug

Added __frem to CRT (wraps fmodf)

---

src/libc/cbrt.c

Having `cbrtf` defined as `powf(x, 1.0f/3.0f)` doesn't work when `x` is negative. I have fixed this by doing `copysignf(powf(fabsf(x), 1.0f/3.0f), x)`, which ensures that the sign of `x` is preserved and that `powf` does not receive negative arguments.
To my knowledge, Calc84Maniac was working on a more accurate `cbrtf` routine in ez80sf. So I won't be adding any other modifications to `cbrtf`.

Fixed cbrtf for negative inputs

---

src/libc/include/tgmath.h
src/libcxx/include/ctgmath

Added `<tgmath.h>`, which allows for operator overloading of `<math.h>` functions in C. Although `_Generic` is a C11 keyword, `<tgmath.h>` works fine in `std=c89` and `std=c99`
```c
sin((float)x) --> sinf
sin((double)x) --> sin
sin((long double)x) --> sinl
sin((int)x) --> sin
pow((float)x, (float)y) --> powf
pow((float)x, (long double)y) --> powl
pow((float)x, (int)y) --> pow
pow((unsigned long long)x, (unsigned long long)y) --> pow
```
Including `<tgmath.h>` or `<ctgmath>` in C++ will include `<cmath>`

added <tgmath.h> to the toolchain

---

examples/standalone_examples/math_test/src/main.c
src/crt/i48abs.src
src/crt/i48div.src
src/libc/include/stdlib.h
src/libcxx/include/cstdlib

`signed __int48 i48abs(signed __int48 n)` is implemented in assembly. The function prototypes for `i48div_t i48div(signed __int48 numer, signed __int48 denom)` have been declared, but the function is not implemented.

Implemented i48abs(int48_t) and added prototypes for i48div

---

src/libc/errno_str.c
src/libc/include/stdio.h
src/libc/include/string.h
src/libc/ti_routines.src
src/libcxx/include/cstdio
src/libcxx/include/cstring
test/standalone/errno/autotest.json
test/standalone/errno/makefile
test/standalone/errno/src/main.c

also adds `ti_routines.src`, which allows for the explicit use of ti's `sprintf` to reduce binary size
identical to https://github.com/CE-Programming/toolchain/pull/546

added perror and strerror along with autotests for them

---

src/libcxx/include/type_traits
src/libcxx/include/utility
src/libcxx/include/version
src/libcxx/type_traits.cpp

C++20 `<version>` provides macros to indicate which parts of libcxx are supported. For now, I have only defined the ones that should be fully supported
```
// c++14
__cpp_lib_exchange_function
__cpp_lib_integral_constant_callable
__cpp_lib_is_null_pointer
// c++17
__cpp_lib_as_const
__cpp_lib_bool_constant
__cpp_lib_logical_traits
__cpp_lib_void_t
// c++20
__cpp_lib_bit_cast
__cpp_lib_endian
__cpp_lib_math_constants
```
A few others are mostly complete such as `__cpp_lib_transformation_trait_aliases` and `__cpp_lib_is_swappable`

C++20 <version> and expanded <type_traits>

---

src/libcxx/include/__config
src/libcxx/include/algorithm
src/libcxx/include/numbers
src/libcxx/include/version

I've added `std::max std::min std::clamp` since they are commonly used C++ functions. Otherwise, the rest of `<algorithm>` can't be implemented since it would require `<iterators>` and a STL

Added <algorithm> for max/min/clamp and fixed LLVM/Clang attributions

---

src/libc/include/__math_def.h
src/libc/include/math.h
src/libcxx/include/__cmath_type_traits
src/libcxx/include/cmath

Changes:
* Functions like `isnan` and `islessequal` now use `_Generic` in C, and use overloads in C++. Additionally, the return value is casted to `int` in C, and `bool` in C++
* All `math.h` functions can be used in the `std::` namespace
* `<cmath>` no longer includes `<type_traits>`, instead using `<__cmath_type_traits>`. `__cmath_is_integral` being identical to `is_integral`
* Including `<math.h>` in C++ now includes `<cmath>`

Fixed the behaviour of including math.h/cmath in C++

---

src/libc/cimagf.src
src/libc/cimagl.src
src/libc/cmplxf.src
src/libc/cmplxl.src
src/libc/conjf.src
src/libc/conjl.src
src/libc/crealf.src
src/libc/creall.src
src/libc/header_test.c
src/libc/include/complex.h
test/floating_point/complex/autotest.json
test/floating_point/complex/makefile
test/floating_point/complex/src/complex_alias.asm
test/floating_point/complex/src/main.c

Added C11 `<complex.h>` prototypes and implemented `CMPLX creal cimag conj` in assembly.
Notes:
* `I` is defined to `_Complex_I`
* `#define complex _Complex` is skipped in C++ to avoid conflicts with `<complex>`/`<ccomplex>` should they be implemented.
* `__mulsc3 __divsc3 __muldc3 __divdc3` are not implemented yet, so I added a warning stating that complex multiplication and division can only be done with `-ffast-math` applied when `<complex.h>` is included.
* `<complex.h>` has not been added to `<tgmath.h>`

Added C11 <complex.h>, along with CMPLX creal cimag conj

---

src/libcxx/header_test.cpp
src/libcxx/include/concepts
src/libcxx/include/type_traits
src/libcxx/include/utility
src/libcxx/include/version
src/libcxx/type_traits.cpp
test/standalone/concepts/autotest.json
test/standalone/concepts/makefile
test/standalone/concepts/src/main.cpp

Changes:
* expanded `<type_traits>`
* added to `<concepts>`
* added C++23 `std::unreachable` to `<utility>`
I have added to `<type_traits>` by replacing `__has_feature(is_foo)` to `__has_builtin(__is_foo)`. From this, almost all of C++17 `<type_traits>` has been implemented except for:
```c++
/* C++11 */
common_type
aligned_storage
aligned_union
result_of
is_trivially_copy_assignable
is_trivially_move_assignable
make_signed
make_unsigned
is_destructable // works in C++20, requires Clang 16 to work in C++11
is_nothrow_destructable // works in C++20, requires Clang 16 to work in C++11
/* C++17 */
is_swappable
is_nothrow_swappable
invoke_result
```
I also replaced existing functions in `<type_traits>` with builtins if possible. I still need to do testing to ensure that all transformations …

expand <type_traits> and <concepts>

---

docs/headers/boot_sprintf.rst
docs/static/printf.rst
src/ce/boot_sprintf.src
src/ce/include/boot_sprintf.h
src/libc/asprintf.src
src/libc/errno_str.c
src/libc/fprintf.src
src/libc/header_test.c
src/libc/include/stdio.h
src/libc/include/string.h
src/libc/include/wchar.h
src/libc/nanoprintf.c
src/libc/printf.src
src/libc/snprintf.src
src/libc/sprintf.src
src/libcxx/include/climits
src/libcxx/include/cstdio
test/standalone/asprintf_fprintf/src/main.c

Currently writing documentation for `boot_sprintf`
One thing to decide on is if `boot_snprintf` and `boot_asprintf` should be defined to `snprintf` and `asprintf` if `HAS_PRINTF = NO`

boot_sprintf docs, fixed fprintf

---

src/libc/include/string.h
src/libc/strlcpy.src
test/standalone/strlcpy/.gitignore
test/standalone/strlcpy/autotest.json
test/standalone/strlcpy/makefile
test/standalone/strlcpy/src/main.c

This PR adds an implementation and tests for `strlcpy`, and corrects its signature in string.h. `strlcpy` is a BSD variant of strncpy that ensures the destination is null-terminated. More info about strlcpy here: https://linux.die.net/man/3/strlcpy

Implement strlcpy

---

src/libc/include/__math_def.h
src/libc/include/cdefs.h
src/libc/include/inttypes.h
src/libc/include/stdlib.h
src/libc/include/tgmath.h
src/libc/isfinitef.src
src/libc/isfinitel.src
src/libc/isinff.src
src/libc/isinfl.src
src/libc/isnanf.src
src/libc/isnanl.src
src/libc/isnormalf.src
src/libc/isnormall.src
src/libc/issubnormalf.src
src/libc/issubnormall.src
src/libc/iszerof.src
src/libc/iszerol.src
src/libc/signbitf.src
src/libc/signbitl.src
src/libc/trigpif.c
src/libc/trigpil.c
src/libcxx/include/__abs_overloads
src/libcxx/include/cmath
src/libcxx/math_test.cpp
test/floating_point/float32_classification/src/main.c
test/floating_point/float64_classification/src/main.c

changes:
* float classification can now be done at compile time in C++. This only worked when I added `constexpr` to the function prototype in C++, so I'm not sure if it can also be done for C.
* Added `__NOEXCEPT __attribute__((const))` to non-standard function prototypes, such as `_fpclassifyf`
* optimzied the float classification routines. Most of them return bool (which gets stored in the carry flag from what I've seen) instead of int
* added sin(pi * x), cos(pi * x), and tan(pi * x) from C23, which allow for accurate range reduction. I didn't add `asinpi acospi atanpi atan2pi` since they are trivial to implement `atan2(y, x) / pi`

float classification is now constexpr, added sinpi/cospi functions

---

docs/static/contributing.rst

MinGW is very outdated, and only provides 32bit versions iirc. MSYS2 MinGW64 should be used instead for Windows (Which is what I've used on both of my Windows 10 machines).
See https://github.com/CE-Programming/toolchain/issues/568
Also, should we mention that `python-sphinx` and `doxygen` are required to build the documentation?

Updated the windows contributing documentation MinGW --> MSYS2 MinGW64

---

src/libcxx/header_test.cpp
src/libcxx/include/__config
src/libcxx/include/concepts
src/libcxx/include/memory
src/libcxx/include/source_location
src/libcxx/include/type_traits
src/libcxx/include/utility
src/libcxx/include/version
src/libcxx/type_traits.cpp
test/standalone/concepts/src/main.cpp

I've added some things since the last pr https://github.com/CE-Programming/toolchain/pull/554
Most of them are based off of Clang's implementation
Added to `<type_traits>`:
* `common_type`
* `is_swappable is_nothrow_swappable`
* `make_signed make_unsigned`
* `common_reference basic_common_reference` (C++20)
Added to `<concepts>`:
* `common_reference_with`
* `common_with`
I did modify `std::move` and `std::swap`, so I'll need to do some additional testing before this gets merged.
I also added the `<memory>` header, using `__builtin_addressof` to implement `addressof`. This function is required for implementing `<functional>` and a few other C++ headers
To make it easier to add Clang code to the toolchain, I've added the following to `<__config>`:
* `_EZCXX_HIDDEN`
* …

improve type_traits and concepts

---

docs/headers/ti/sprintf.rst
src/ce/include/ti/sprintf.h
src/libc/asprintf.src
src/libc/boot_vsprintf.c
src/libc/boot_vsprintf.src
src/libc/include/stdio.h
src/libc/snprintf.src
src/libc/sprintf.src
src/libc/vsprintf.src
test/graphx/zx0/.gitignore
test/standalone/asprintf_fprintf/autotest.json
test/standalone/asprintf_fprintf/makefile
test/standalone/asprintf_fprintf/src/main.c

Changes:
* `boot_vsprintf` was added, allowing for `boot_snprintf boot_asprintf` to be implemented as functions instead of macros

Added `boot_vsprintf`

---

src/libc/atan2f.c
src/libc/atan2l.c
src/libc/atanf.c
src/libc/atanl.c
src/libc/cosf.src
src/libc/floorf.c
src/libc/include/__math_def.h
src/libc/sinf.c
src/libc/sinf.src

Changes:
* sinf and cosf have been optimized. Additionally, the result is now clamped to [-1,+1]
* atan and atan2 (float and long double) have been optimized by reducing the amount of times `y < 0.0f` is checked
* passing NULL into modf is undefined behavior, so I added `__attribute__((nonnull(2)))` to `modf` to let the user know that they cannot pass NULL for the second argument

optimized sinf, cosf, atan, and atan2

---

src/libc/ez80_builtin.src
src/libc/include/ez80_builtin.h
src/libc/include/stdbit.h
src/libcxx/include/bit
src/libcxx/include/version
test/standalone/ez80_builtin/src/main.c
test/standalone/stdbit/autotest.json
test/standalone/stdbit/src/main.cpp

Added `__builtin_clrsb*` and `__builtin_parity*` were missing for some types, so they have been implemented under `__ez80_clrsb*` and `__ez80_parity*`.
Otherwise, I finished the rest of C++20 `<bit>`

Implemented the rest of C++20 <bit>, and added __ez80_clrsb* and __ez80_parity*

---

src/graphx/graphx.h

I've added a few function `__atrribute__`'s to `graphx.h`. This can help with optimization, and safety.
Changes:
* `gfx_AllocSprite` and `gfx_ConvertToNewRLETSprite` take a function pointer to a malloc routine, so I've added `__nonnull__` to that parameter since these routines do not check if the function pointer is `NULL`.
* `gfx_Lighten` and `gfx_Darken` are `__const__` functions as the same inputs will always generate the same output.
* `gfx_GetTextX`, `gfx_GetTextY`, `gfx_GetCharWidth`, and `gfx_GetStringWidth` are `__pure__` functions, as they read from non-volatile addresses.
* A bunch of the sprite routines say `@note sprite_in and sprite_out cannot be the same`, so I've added `__restrict` to both parameters, which can then allow the compiler to warn about it.
* `gfx_TilePtr` and …

Added __attribute__ nonnull/pure/const to some GraphX prototypes

---

src/libcxx/include/bit
test/standalone/stdbit/src/data.asm
test/standalone/stdbit/src/data.h
test/standalone/stdbit/src/main.cpp
test/standalone/stdbit/src/test.c

Fixed `std::bit_ceil`, and added more tests for `<stdbit.h>` and `<bit>`

Fixed behaviour of C++ <bit>

---

src/libcxx/include/bit
test/standalone/stdbit/src/main.cpp

calc84maniac suggested this code to allow `std::bit_ceil` to avoid UB
`(value < 2 ? 1 : 2 << (stdc_bit_width(value - 1) - 1)`

Fixed std::bit_ceil, made it behave the same as C23 stdc_bit_ceil

---

docs/headers/ti/sprintf.rst
src/libc/boot_vsprintf.c
src/libc/nanoprintf.c
test/standalone/asprintf_fprintf/src/main.c

`boot_snprintf` had a call to `vnsprintf` instead of `boot_vnsprintf` by mistake.
The user is unlikely to directly call `vprintf` or `vfprintf`, so they have been forced inlined into `printf` and `fprintf`. This saves space as code for `vprintf` and `vfprintf` won't need to be linked in most cases. I would've done this with `vasprintf`, and `vsnprintf`, but they are considerably larger
```c++
__attribute__((__always_inline__))
int _vprintf_c(const char *__restrict format, va_list vlist)
{
return npf_vpprintf(npf_putc_std, NULL, format, vlist);
}
int _printf_c(char const *__restrict format, ...) {
va_list va;
va_start(va, format);
int const rv = _vprintf_c(format, va);
va_end(va);
return rv;
}
```

fixed boot_snprintf, and nanoprintf linking bugs

---

src/graphx/graphx.asm

Inspired by #595, I took a look at optimizing GraphX's rounded-down signed division routine. Since it wasn't initially designed to round down and the rounding fixup was added later, I thought about ways to make it round down from the start. Eventually, I came up with the idea of transforming the signed division into unsigned, which always rounds down. So, after conditionally negating both the dividend and divisor such that the divisor is positive, the unsigned division can be done as follows:
If x >= 0: Return x / y
If x < 0: Return ((y * 2^24) + x) / y
This setup can be done via an optimized first iteration where the remainder register is initialized to either 0 or y-1 based on the sign bit of the dividend, and that sign bit of the dividend is directly output into the sign bit of the …

Optimized _DivideHLBC, fixed incorrect behavior for INT_MIN inputs

---

src/libc/bzero.src
src/libc/include/string.h
src/libc/memcpy.src
src/libc/mempcpy.src
src/libc/memset.src
src/libc/strlen.src
src/libcxx/include/cstring
test/standalone/asprintf_fprintf/src/main.c
test/standalone/asprintf_fprintf/src/rename.asm

Changes:
- optimized `memcpy` and `mempcpy`
- optimized `strlen`
- optimized `memset` for speed (Adds 6 bytes and 6F, but removes 5R + 12W in full execution case)
- Added `bzero`. This copies zeros from `0xE40000` which has less read states, thereby making it significantly faster than `memset`.
`memcpy` and `mempcpy` were optimized by turning `NC \ sbc hl, hl \ sbc hl, bc \ ret z` into `C \ sbc hl, hl \ add hl, bc \ ret nc`, saving 1 byte and 1F in all cases. The carry flag is set by doing `ld iy, -1 \ add iy, sp` instead of the usual `ld iy, 0 \ add iy, sp`

Optimized memcpy and mempcpy

---

src/crt/cttz.src
src/libc/ez80_builtin.src
test/standalone/ez80_builtin/src/main.c

I've implemented optimized count-trailing-zero libcalls, and I have an ez80-clang commit ready to push to make it use them. They've also been added to ez80_builtin implementations where applicable, and tested via ez80_builtin/stdbit tests.

Add count-trailing-zero libcalls

---

src/graphx/graphx.asm

I was comparing `__imulu` to `_MultiplyHLBC`. Since there is no branching in either routine, I could remove instructions that were common to both routines. I then found that `__imulu` is faster and smaller. With the only difference being that it preserves `AF`, while `_MultiplyHLBC` destroys `AF`.
```asm
__imulu
; 7 bytes + 7F + 6R + 3W
push	af
add	a, h
ld	d, b
ld	d, a
ld	e, c
pop	de
pop	af
_MultiplyHLBC:
; 18 bytes + 18F + 3R + 3W
push	iy
ld	iy, 0
add	iy, de
add	iy, de
inc	sp
ld	c, 0
lea	hl, iy + 0
pop	iy
```
Based on this, `_MultiplyHLBC` has been replaced with the code for `__imulu`. It seems like `A` doesn't need to be preserved based on the routines that use `_MultiplyHLBC`, so it seems safe to comment out `push af \ pop af`.
In total this should remove 13 bytes + 13F + 3W from …

Optimized _MultiplyHLBC

---

src/libc/memrchr.src
src/libc/os.src
src/libc/strcmp.src
src/libc/strncmp.src
test/standalone/asprintf_fprintf/src/main.c
test/standalone/asprintf_fprintf/src/rename.asm
test/standalone/strlcpy/autotest.json
test/standalone/strlcpy/makefile

Optimized `strcmp` and `strncmp`. Also added `memrchr`
`strncmp` has a linear speedup compared to Ti's routine (less clock cycles per character compared), making it much faster
`strcmp` has a constant speedup compared to Ti's routine (same clock cycles per character compared, but takes less clock cycles in total), which may be worth it when multiple short string comparisons need to be performed, such as when parsing text/scripts.

Optimized strcmp and strncmp. Also added memrchr

---

src/libc/include/math.h
src/libcxx/include/memory
src/libcxx/math_test.cpp
test/floating_point/compiletime_classification/autotest.json
test/floating_point/compiletime_classification/makefile
test/floating_point/compiletime_classification/src/main.c
test/floating_point/compiletime_classification/src/test.asm

float classification routines can now be evaluated at compile time in C using `__builtin_constant_p`.  If a function call is emitted in the auto-test code (hence not constant folded), it will conflict with some functions I've defined in `test.asm`. This will cause linker error resulting in the auto-test failing.
I also fixed `math_test.cpp` and `constexpr addressof`

float classification routines can now be constant folded in C

---

src/crt/ftod.src
src/crt/i48abs.src

ftod was made 4 bytes smaller. This makes zero/normal/NaN/infinite 2F faster, and subnormal 1F faster
I also optimized the placement of the tailcall in i48abs to lower the clock cycle difference between the positive and negative cases.

optimized ftod and i48abs

---

src/libc/ldexpf.src
test/floating_point/complex/src/main.c
test/floating_point/float32_classification/src/main.c
test/floating_point/float32_frexp/src/main.c
test/floating_point/float32_ilogb/src/main.c
test/floating_point/float32_ldexp/src/main.c
test/floating_point/float32_math/src/main.cpp
test/floating_point/float32_modf/src/main.c
test/floating_point/float32_to_float64/src/main.c
test/floating_point/float32_trunc/src/main.c
test/floating_point/float64_arithmetic/src/main.cpp
test/floating_point/float64_classification/src/main.c
test/floating_point/float64_frexp/src/main.c
test/floating_point/float64_from_integer/src/main.c
test/floating_point/float64_ilogb/src/main.c
test/floating_point/float64_ldexp/src/main.c
test/floating_point/float64_math/src/main.cpp
test/floating_point/float64_rounding/src/main.c
test/floating_point/float64_to_float32/src/main.c
test/floating_point/float64_to_integer/src/main.c
test/floating_point/float64_trunc/src/main.c
test/floating_point/ultof/src/main.c

ldexpf had a small bug where it did (expon < 0) instead of (expon <= 0). So I fixed that
I also replaced `printf` with `boot_sprintf` in some autotests to reduce the chances of GDB1 errors. Since using `boot_sprintf` makes `DEMO.8xp` smaller by ~8kb

fixed ldexpf, and reduced GDB1 autotest errors

---

src/graphx/graphx.asm

Saves around 18 bytes in total. The setup code is faster, but the loop code is unchanged

optimized graphx circle routines

---

src/graphx/graphx.asm
src/graphx/graphx.h

This is in its own commit due to the complexity of `gfx_RotateScaleSprite` and `gfx_RotatedScaledSprite(Transparent)_NoClip`.
The inner loop of `gfx_RotatedScaledSpriteTransparent_NoClip` is 8F faster when a pixel is drawn. I also believe that creating a clipped variant of this routine is possible with a constant performance penalty.
I have fixed most of the issues outlined in https://github.com/CE-Programming/toolchain/issues/612. There are a few limitations to note:
- The sprite will render incorrectly if the output is larger than 255x255. This is not worth fixing however, since a 256x256 sprite doesn't fit onto a 320x240 screen anyways.
- input sprites larger than 210x210 (`255 * (sqrt(8) - 2)` or ~211.2489) may experience texture wrapping. This should be harmless, as shown below with …

Optimized sprite rotation routines

---

examples/library_examples/lcddrvce/column_major/.gitignore
examples/library_examples/lcddrvce/column_major/makefile
examples/library_examples/lcddrvce/column_major/src/main.c

Rewrite of the previous attempt: https://github.com/CE-Programming/toolchain/pull/609
This demo shows how `lcddrvce` can be used to set the screen to column-major mode. It is similar to the `graphx/buffered_cube` example, but shows how column-major mode can be used to remove diagonal screen tearing.
Not exactly sure what comments I should add to the line drawing code.

Added a column-major demo for lcddrvce

---

src/crt/imulu_b.src
src/crt/imulu_b_fast.src
src/crt/lmulu_b.src
src/crt/lmulu_b_fast.src
src/crt/os.src
src/crt/smulu_b.src
src/crt/smulu_b_fast.src
test/standalone/mulu_b/autotest.json
test/standalone/mulu_b/makefile
test/standalone/mulu_b/src/crt_wrap.asm
test/standalone/mulu_b/src/main.c

Added some CRT routines (along with `_fast` variants) for 32/24/16bit * 8bit unsigned multiplication.
`imulu_b`: `UHL = UHL * A` (same as Zilog's/Ti's `imul_b`)
`smulu_b`: `HL = HL * A`
`lmulu_b`: `EUHL = EUHL * A`
`lmulu_b` copies the calling convention of `ladd_b`. Not quite sure what calling convention would be used for `i48mulu_b`.
```
smulu       : 20*r(PC) +  6*r(SPL) +  3*w(SPL) + 13
smulu_b     : 15*r(PC) +  6*r(SPL) +  3*w(SPL) +  9
imulu       : 49*r(PC) + 15*r(SPL) + 12*w(SPL) + 25
imulu_b     : 32*r(PC) + 12*r(SPL) +  9*w(SPL) + 13
lmulu       : 93*r(PC) + 15*r(SPL) + 15*w(SPL) + 41
lmulu_b     : 43*r(PC) + 12*r(SPL) +  9*w(SPL) + 13
```

added imulu_b lmulu_b and smulu_b

---

src/libc/asprintf.src
src/libc/bzero.src
src/libc/snprintf.src
src/makefile.mk

Removed usage of the `0xE40000` address from standard/common C functions (such as `bzero`). 
`boot_(v)snprintf` and `boot_(v)asprintf` still use the `0xE40000` address in their implementation. Which should be okay, since they are platform specific functions. 
Since `(v)snprintf` and `(v)asprintf` are standard/common C functions, I have removed the option to have them link to `boot_(v)snprintf` and `boot_(v)asprintf`.

fixed useages of the hardware specific 0xE40000 address

---

src/crt/i48add.src
src/crt/i48add_1.src
src/crt/i48and.src
src/crt/i48bswap.src
src/crt/i48cmps.src
src/crt/i48cmpu.src
src/crt/i48cmpzero.src
src/crt/i48divs.src
src/crt/i48divu.src
src/crt/i48dvrmu.src
src/crt/i48mulu.src
src/crt/i48neg.src
src/crt/i48not.src
src/crt/i48or.src
src/crt/i48popcnt.src
src/crt/i48rems.src
src/crt/i48remu.src
src/crt/i48shl.src
src/crt/i48shr.src
src/crt/i48sub.src
src/crt/i48sub_1.src
src/crt/i48xor.src

fixes white-space in i48 CRT routines:
- `add hl, de ; foo` --> `add\thl, de\t\t; foo` and etc
- adding new lines to the end of files
- fixing small typos
I also added the cycle counts for some i48 CRT routines.

Format i48 crt

---

src/libc/memmove.src
src/libc/os.src
test/standalone/asprintf_fprintf/src/main.c
test/standalone/asprintf_fprintf/src/rename.asm

Optimized `memmove`, as it appears to be used a lot by C++ code.

optimized memmove

---

src/crt/lland.src
src/crt/lland_fast.src
src/crt/llor.src
src/crt/llor_fast.src
src/crt/llxor.src
src/crt/llxor_fast.src

Saved 1 byte and 1F in `lland`, `llor`, `llxor` and their fast variants

optimize i64 bitwise operations
